platform :ios, '8.0'
target 'BFProjectTools' do
pod 'AFNetworking', '~> 3.1.0'
pod 'FMDB', '~> 2.5'
pod 'IDMPhotoBrowser', '~> 1.8.4'
pod 'QBImagePickerController', '~> 3.4.0'
pod 'BEMSimpleLineGraph'


end 
